# Generated by Django 3.1.7 on 2021-04-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, help_text='Family| Bachelor | Corporate | Individual...etc', max_length=50, null=True, verbose_name='Customer Type')),
            ],
            options={
                'verbose_name': 'Customer Type',
                'verbose_name_plural': 'Customer Types',
            },
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Source')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Source URL')),
                ('thumbnail', models.ImageField(blank=True, default='thumbnails/1.jpg', null=True, upload_to='thumbnails/', verbose_name='Thumbnail')),
                ('logo', models.ImageField(blank=True, default='logo/1.jpg', null=True, upload_to='logo/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Lead Source',
                'verbose_name_plural': 'Lead Sources',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Location Name')),
                ('pincode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Pin Code')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['-id'],
            },
        ),
    ]
